
package awt_actionlistiner;
import java.awt.*;
import java.awt.event.*;


class MyFrame extends Frame implements ActionListener{

    Label l,u;
    Button b;
    int count=0;
    String action;
    
    MyFrame(){
        
        super("my frame");
        this.l=new Label("count: "+count);
        
        this.b=new Button("click");
        b.addActionListener(this);
        
        this.u=new Label("action generated by:"+action);
        
        setLayout(new FlowLayout());
        
        add(l);
        add(b);
        add(u);
        
    }
    
    
    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
        action=e.getActionCommand();
        count++;
        l.setText(""+count);
        u.setText("action generated by:"+action);
        
        
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    
    
}






public class AWT_ActionListiner {

    
    public static void main(String[] args) {
        
        
        MyFrame frame = new MyFrame();
        frame.setSize(400,200);
        frame.setVisible(true);
        
        
    }
    
}
